import { Experience } from "@/types";

import { getBrandById } from "./brands";
import { getEmploymentTypeById } from "./employmentTypes";

const experiences: Experience[] = [
  {
    from: new Date(2022, 9),
    to: "Present",
    jobTitle: "Frontend Engineer",
    company: getBrandById("tecpal"),
    employmentType: getEmploymentTypeById("fullTime"),
    jobDuties: [
      "Facilitated the seamless migration of Vue apps from a legacy WordPress API to a modern RESTful API.",
      "Orchestrated the successful implementation of features in Vue apps, including an authorization system and a shopping list.",
      "Conducted technical review and spearheaded proof-of-concept development for web application migration from Vue to Astro and Next.js.",
      "Pioneered the implementation of Turborepo, establishing the fundamental groundwork for the successful transition.",
    ],
    supportingDocuments: [],
    relevantSkills: [
      "Vue",
      "Vuetify",
      "Quasar",
      "Vuex",
      "Pinia",
      "WordPress",
      "TypeScript",
      "Turborepo",
      "React",
      "Next.js",
      "Create React App",
      "MUI",
      "React Query",
    ],
  },
  {
    from: new Date(2022, 4),
    to: new Date(2022, 8),
    jobTitle: "Programmer (Business and Administrative Systems)",
    company: [getBrandById("edps"), getBrandById("ha")],
    employmentType: getEmploymentTypeById("contract"),
    companyTemplate: "{0} | Seconded to {1}",
    jobDuties: [
      "Managed ha.org.hk and multiple intranet web apps, effectively catering to the needs of 100+ staff and 7M+ Hong Kong residents.",
      "Orchestrated the strategic planning and timely execution of web app OS and DB migration within 1 week.",
    ],
    supportingDocuments: [],
    relevantSkills: ["ASP", "jQuery UI", "Microsoft SQL Server"],
  },
  {
    from: new Date(2021, 7),
    to: new Date(2022, 4),
    jobTitle: "Programmer (Database Management System)",
    company: [getBrandById("edps"), getBrandById("ha")],
    companyTemplate: "{0} | Seconded to {1}",
    employmentType: getEmploymentTypeById("contract"),
    jobDuties: [
      "Played an active role in conducting a DB knowledge-sharing session and engaging audiences of 100+ technical professionals.",
      "Implemented and sustained a Bitrix24 site for managing training materials, guidelines, and documentation, resulting in a 20% increase in work efficiency.",
      "Architected and programmed a database health check system utilizing React, Express, and MySQL, streamlining SRE processes and decreasing system recovery time.",
      "Provided support and guidance to 10+ application teams on MySQL deployment and maintenance.",
      "Architected and programmed a web app with React, Express, and MySQL that visualized database CPU utilization, resulting in a 30% increment in productivity.",
      "Conducted a POC on data virtualization utilizing the Delphix DataOps platform, bolstering support for 3 types of DBs and 50+ DB instances.",
    ],
    supportingDocuments: ["haSc3RefLetter", "lunchAndLearn"],
    relevantSkills: [
      "MySQL",
      "Microsoft SQL Server",
      "Oracle Database",
      "Sybase ASE",
      "Delphix",
      "React",
      "Create React App",
      "MUI",
      "Redux Toolkit",
      "React Hook Form",
      "Prism.js",
      "Express",
      "OpenShift",
    ],
  },
  {
    from: new Date(2019, 6),
    to: new Date(2021, 7),
    jobTitle: "Junior Programmer (Database Management System)",
    company: [getBrandById("edps"), getBrandById("ha")],
    companyTemplate: "{0} | Seconded to {1}",
    employmentType: getEmploymentTypeById("contract"),
    jobDuties: [
      "Provided support and guidance to 3+ application teams on MySQL deployment and maintenance.",
      "Maintained database management web application",
      "Implemented time off application system using React, Express, and MySQL, benefiting 20+ team members and reducing admin workload by 90%",
      "Developed a Java-based application for managing database passwords that supports 3 types of databases.",
      "Conducted a POC on data virtualization utilizing the Delphix DataOps platform, bolstering support for 2 types of DBs and 30+ DB instances.",
    ],
    supportingDocuments: [],
    relevantSkills: [
      "MySQL",
      "Sybase ASE",
      "Delphix",
      "React",
      "MUI",
      "Redux Toolkit",
      "Express",
    ],
  },
  {
    from: new Date(2018, 5),
    to: new Date(2018, 7),
    jobTitle: "Summer Internship (Software Development)",
    company: getBrandById("versitech"),
    employmentType: getEmploymentTypeById("internship"),
    jobDuties: [
      "Collaborated with software engineers to design a comprehensive test suite for the E-Form Filler.",
      "Architected and programmed an installer for the E-Form Filler utilizing NSIS MUI2.",
      "Revamped a legacy MPF mobile app, originally developed three years prior, using React Native as a replacement for Cordova.",
    ],
    supportingDocuments: [],
    relevantSkills: [
      "NSIS MUI2",
      "React Native",
      "NativeBase",
      "React Navigation",
      "MobX",
    ],
  },
  {
    from: new Date(2017, 6),
    to: new Date(2017, 8),
    jobTitle: "Student Research Assistant",
    company: getBrandById("publicHealthHku"),
    employmentType: getEmploymentTypeById("partTime"),
    jobDuties: [
      "Designed and programmed a JavaFX app for executing bioinformatics analyses.",
    ],
    supportingDocuments: ["hkuMedRaRefLetter"],
    relevantSkills: ["JavaFX", "ControlsFX"],
  },
  {
    from: new Date(2017, 0),
    to: new Date(2017, 3),
    jobTitle: "Teaching Assistant",
    company: getBrandById("engineeringHku"),
    employmentType: getEmploymentTypeById("partTime"),
    jobDuties: [
      "Conducted tutorial sessions for a C++ programming course, providing instruction to a class of 20+ students.",
    ],
    supportingDocuments: ["hkuEngTaRefLetter"],
    relevantSkills: ["C++"],
  },
];

export default experiences;
