name: Lighthouse

on: deployment_status

jobs:
  lighthouse:
    if: ${{ github.event.deployment_status.state == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - run: mkdir -p ${{ github.workspace }}/tmp/artifacts

      - name: Lighthouse
        uses: foo-software/lighthouse-check-action@master
        id: lighthouse
        with:
          urls: ${{ github.event.deployment_status.target_url }}
          device: mobile
          outputDirectory: ${{ github.workspace }}/tmp/artifacts
          prCommentEnabled: true
          prCommentSaveOld: true
          commentUrl: https://api.github.com/repos/${{ github.repository }}/commits/${{ github.sha }}/comments
          gitHubAccessToken: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload artifacts
        uses: actions/upload-artifact@master
        with:
          name: Lighthouse reports
          path: ${{ github.workspace }}/tmp/artifacts

      - name: Verify Results
        uses: foo-software/lighthouse-check-status-action@master
        with:
          lighthouseCheckResults: ${{ steps.lighthouse.outputs.lighthouseCheckResults }}
          minAccessibilityScore: "100"
          minBestPracticesScore: "92"
          minSeoScore: "92"
