name: Lighthouse

on: deployment_status

jobs:
  lighthouse:
    if: ${{ github.event.deployment_status.state == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - run: mkdir -p ${{ github.workspace }}/tmp/artifacts

      - name: Lighthouse
        uses: foo-software/lighthouse-check-action@9
        with:
          outputDirectory: ${{ github.workspace }}/tmp/artifacts
          url: ${{ github.event.deployment_status.target_url }}
          gitHubAccessToken: ${{ secrets.GITHUB_TOKEN }}
          prCommentEnabled: true
          prCommentSaveOld: true

      - name: Upload artifacts
        uses: actions/upload-artifact@3
        with:
          name: Lighthouse reports
          path: ${{ github.workspace }}/tmp/artifacts
