name: Lighthouse

on: deployment_status

jobs:
  lighthouse:
    if: ${{ github.event.deployment_status.state == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      
      - run: mkdir -p ${{ github.workspace }}/tmp/artifacts

      - name: Lighthouse
        uses: foo-software/lighthouse-check-action@master
        with:
          outputDirectory: ${{ github.workspace }}/tmp/artifacts
          urls: ${{ github.event.deployment_status.target_url }}
          gitHubAccessToken: ${{ secrets.GITHUB_TOKEN }}
          device: mobile
          prCommentEnabled: true
          prCommentSaveOld: true
          minPerformanceScore: "90"
          minAccessibilityScore: "98"
          minBestPracticesScore: "100"
          minSeoScore: "100"

      - name: Upload artifacts
        uses: actions/upload-artifact@master
        with:
          name: Lighthouse reports
          path: ${{ github.workspace }}/tmp/artifacts
